###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Clements, CS 165
# Author:
#     Aaron Jones
# Summary:
#     This program will take in the user’s information.
#		Specifically, it will ask for the Address, Customer,
#		Product, and the Order. Continually the program will
#		use multiple classes that store values in the private
#		Member data and pass these values to the class-specific
#		getters and setters. Overall this program will
#		demonstrate the uses of Object-Oriented design and
#		functionality.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp
