###############################################################
# Program:
#     Checkpoint 05a, Getters and Setters
#     Brother Clemons, CS165
# Author:
#     Aaron Jones
# Summary:
#     Summaries are not necessary for checkpoint assignments.
###############################################################

a.out : money.h money.cpp check05a.cpp
	g++ money.cpp check05a.cpp
        tar cvf check05a.tar makefile *.cpp *.h

clean:
  rm *.out
  rm *.tar
